# Generated by Django 3.2.4 on 2021-06-06 01:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 1, 58, 30, 885242, tzinfo=utc)),
        ),
    ]
